# Generated by Django 3.2.9 on 2021-11-28 12:14

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion
import yangpago_slack.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_simple_slack_app', '0002_auto_20211128_1214'),
        ('yangpago_slack', '0002_auto_20200628_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translatelog',
            old_name='from_lang',
            new_name='source_lang_code',
        ),
        migrations.RenameField(
            model_name='translatelog',
            old_name='to_lang',
            new_name='target_lang_code',
        ),
        migrations.RenameModel(
            old_name='PapagoPlan',
            new_name='YangpagoPlan',
        ),
        migrations.RenameModel(
            old_name='PapagoSlackUser',
            new_name='YangpagoSlackUser',
        ),
        migrations.RenameModel(
            old_name='PapagoSlackTeam',
            new_name='YangpagoSlackTeam',
        ),
        migrations.AlterField(
            model_name='translatelog',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yangpago_slack.yangpagoslackteam'),
        ),
        migrations.AlterField(
            model_name='translatelog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yangpago_slack.yangpagoslackuser'),
        ),
    ]
